package io.blinkhouse.core.query.metamodel;

import io.blinkhouse.core.query.ast.ColumnRef;
import io.blinkhouse.core.query.ast.OrderSpec;

/**
 * A typed column descriptor generated by the BlinkHouse annotation processor.
 *
 * <p>Instances are held as {@code public static final} fields in generated
 * {@code Xxx_} metamodel classes (e.g. {@code PageView_.ts}). They wrap a
 * {@link ColumnRef} and expose the column name and value type, enabling
 * compile-time-checked query construction.
 *
 * <p>The string-based {@code col("ts")} API always works without the processor (ADR-05).
 *
 * @param <E> the entity type that owns the column
 * @param <V> the Java value type of the column
 */
public final class Column<E, V> {

    private final ColumnRef ref;
    private final Class<V> valueType;

    /**
     * Constructs a column descriptor.
     *
     * @param name      the column name (must match the stored column name)
     * @param valueType the Java value type
     */
    public Column(String name, Class<V> valueType) {
        this.ref = ColumnRef.of(name);
        this.valueType = valueType;
    }

    /**
     * Returns the underlying {@link ColumnRef} for use in query expressions.
     *
     * @return the column reference
     */
    public ColumnRef ref() {
        return ref;
    }

    /**
     * Returns the Java value type of this column.
     *
     * @return the value type class
     */
    public Class<V> valueType() {
        return valueType;
    }

    /**
     * Returns the column name.
     *
     * @return the column name
     */
    public String name() {
        return ref.name();
    }

    /**
     * Creates an equality predicate for this column.
     *
     * @param value the value to compare
     * @return an equality predicate
     */
    public io.blinkhouse.core.query.ast.Comparison eq(V value) {
        return ref.eq(value);
    }

    /**
     * Creates an inequality predicate for this column.
     *
     * @param value the value to compare
     * @return an inequality predicate
     */
    public io.blinkhouse.core.query.ast.Comparison neq(V value) {
        return ref.neq(value);
    }

    /**
     * Creates a less-than predicate for this column.
     *
     * @param value the value to compare
     * @return a less-than predicate
     */
    public io.blinkhouse.core.query.ast.Comparison lt(V value) {
        return ref.lt(value);
    }

    /**
     * Creates a less-than-or-equal predicate for this column.
     *
     * @param value the value to compare
     * @return a less-than-or-equal predicate
     */
    public io.blinkhouse.core.query.ast.Comparison lte(V value) {
        return ref.lte(value);
    }

    /**
     * Creates a greater-than predicate for this column.
     *
     * @param value the value to compare
     * @return a greater-than predicate
     */
    public io.blinkhouse.core.query.ast.Comparison gt(V value) {
        return ref.gt(value);
    }

    /**
     * Creates a greater-than-or-equal predicate for this column.
     *
     * @param value the value to compare
     * @return a greater-than-or-equal predicate
     */
    public io.blinkhouse.core.query.ast.Comparison gte(V value) {
        return ref.gte(value);
    }

    /**
     * Creates an ascending order specification for this column.
     *
     * @return an ascending OrderSpec
     */
    public OrderSpec asc() {
        return ref.asc();
    }

    /**
     * Creates a descending order specification for this column.
     *
     * @return a descending OrderSpec
     */
    public OrderSpec desc() {
        return ref.desc();
    }
}
